blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Questions & Discussion
    url: https://github.com/victorhuangwq/story-to-manga/discussions
    about: Ask questions and discuss ideas with the community